### ISSUE TITLE
Loose ends from OptimizationSystem

### ISSUE THREAD

**Issue by ValentinKaisermayer** [SciML/ModelingToolkit.jl#1786]
- [x] Handling of nested constraints, see #1785 
- [x] Proper inequality constraint handling, see discussion in #1660, see #1799 and https://github.com/JuliaSymbolics/Symbolics.jl/pull/717
The definition of inequality constraints is decoupled from the definition of the actual bounds. Also one has to specify an equality constraint first even if it ends up as inequality. As much as possible should be specified during the modelling phase.
```julia
@variables x y
@parameters a b
loss = (a - x)^2 + b * (y - x^2)^2
cons = [
    x^2 + y^2 ~ 0, 
    y * sin(x) - x ~ 0
]
sys = OptimizationSystem(loss, [x, y], [a, b], name = :sys, constraints = cons)
prob = OptimizationProblem(sys, [x => 0.0, y => 0.0], [a => 1.0, b => 100.0],
                           lcons = [-1.0, -1.0], ucons = [500.0, 500.0])
```
- [x] Proper handling of variable bounds, see  #1799
Again this is decoupled from the system modelling and is specified during construction of the `OptimizationProblem`. However, MTK has already a way of specifiying box constraints on variables via e.g., `@variables x [bounds=(-1.0, 1.0)]`. 
- [x] Handling of discrete and logical constraints, e.g., `@variables x [binary=true]`. see #1798 and https://github.com/SciML/SciMLBase.jl/issues/270
- [x] Support for `MathOptInterface.AbstractOptimizer` that do not support `MathOptInterface.NLPBlock`. If a problem is linear or quadratic why use an NLP solver? However, I see this more of an issue for `OptimizationMOI.jl`. This is important for MPCs which are typically QPs. https://github.com/SciML/Optimization.jl/issues/369
- [x] Convenient accessing solutions. For `ODEProblem` one can do `sol[x]`.

**Comment by ChrisRackauckas** [comment]
Thanks, this is a nice list.

**Comment by ValentinKaisermayer** [comment]
Yeah!
