### ISSUE TITLE
Clocks TODO

### ISSUE THREAD

**Issue by baggepinnen** [SciML/ModelingToolkit.jl#1939]
- [x] Hook up codegen when `ODEFunction` is called
- [x] Do something with all the data saved by discrete-time partitions
- [x] Clean up old code generation for discrete-time systems
    - [x] https://github.com/SciML/ModelingToolkit.jl/pull/2413
- [x] Get rid of old, ill-defined discrete operators
    - [x] https://github.com/SciML/ModelingToolkit.jl/pull/2413
- [x] Set initial condition for discrete variables with a sane syntax
- [x] code generation with more than one discrete-time partition
- [x] add tests for multiple clock rates
- [x] Handle negative shifts, #2359 
- [x] Store solution to discrete-time partitions and make it accesible through `idxs` keyword
- [x] handle plotting of discrete-time data with `steppost + marker` appearance
- [x] Specification of data types of state variables and parameters in the MTK model, e.g., `Int, Float64` etc. This type has to be configurable by the user instantiating a block, e.g., the user can select whether an integer variable is `Int64 / Int32` etc., #2491 
- [x] Introduce `Sample` and `Hold` blocks in MTKstdlib, https://github.com/SciML/ModelingToolkitStandardLibrary.jl/pull/242
- [ ] Introduce super and sub sampling #2744 
- [ ] Introduce Clock block that can be connected to discrete-time components to associate them with a clock
- [x] Handle calls to `sampletime` in equations that have `InferredDiscrete`  time domain. This should use a connected clock if available, otherwise set the domain to inferred. #2690
- [x] Test discrete-time partitions that include both positive and negative shifts
- [x] Add documentation
    - [x] Mention implicit `(k)` index for non-indexed variables
    - [x] Nail down the semantics of the shift index w.r.t. initial conditions. The simulation starts at shift index `k`, and the initial condition is all indices less than `k`.
    - [x] https://github.com/SciML/ModelingToolkit.jl/pull/2410
- [x] Add tutorials
- [x] https://github.com/SciML/ModelingToolkit.jl/issues/2356
- [ ] Test inversion of discrete-time model.
