### ISSUE TITLE
Short term milestones

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkit.jl#206]
- [x] N-tensor generation
- [x] Sparse N-tensor generation
- [x] Optimized sparse code generation from build_function
- [ ] Document the usage of these derivative functions and the function builder.
- [x] FileIO output .jl files from MTK

**Comment by ChrisRackauckas** [comment]
Writing to a file is just `write("function.jl", string(func))`
