### ISSUE TITLE
DAE Model Translation and Symbolic Processing Meta Issue

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkit.jl#338]
This is a meta-issue to track the progress on full DAE symbolic numerics a-la https://www.claytex.com/tech-blog/model-translation-and-symbolic-manipulation/ . 

- [x] Index reduction https://github.com/SciML/ModelingToolkit.jl/issues/18
- [x] Alias removal
- [ ] Tearing https://github.com/SciML/ModelingToolkit.jl/issues/181
- [x] Specialized Wfact methods we pre-solve linear system portions and split the nonlinear systems

**Comment by ChrisRackauckas** [comment]
We can leave dynamic state selection (https://www.modelica.org/events/workshop2000/proceedings/old/Mattsson.pdf) as a later and separate transformation.
